### ISSUE TITLE
How to access fields internally?

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/field_serializer#3]
Sometimes fields depend on other fields. For example, in the Nigerian Assembly scraper, the `area` is the [constituency plus the state](https://github.com/everypolitician-scrapers/nigeria-national-assembly/blob/master/scraper.rb#L100-L102).

There should be some way to access the other fields as if they were plain methods, rather than having the extra indirection of actually making methods for them.

**Comment by chrismytton** [comment]
> There should be some way to access the other fields as if they were plain methods, rather than having the extra indirection of actually making methods for them.

This seems like the best way to go, I've done a pull request for that here #5.
